### PR TITLE
Fix Hell Knight by searching for C1 suffix sprites

### PR DESCRIPTION
**Pull request by selliott512**
For Freedoom 2 the Hell Knight was appearing as a "?" both in the 3D view and in the things browser. The A1 sprite is mirrored in Doom 2, but not Freedoom 2:
```
wad-to-lump.py -sv doom2.wad | grep BOS2A1
   7411172       2288  BOS2A1C1   True
wad-to-lump.py -sv freedoom2.wad | grep BOS2A1
  13415544       2940    BOS2A1   True
```

Incidentally, it would be helpful if Eureka tagged releases. I found the git hashes for the two most recent releases by comparing to source archives, in case you want to do it:
```
git tag -m 'eureka-editor 1.27b' v1.27b ed8309a2d47e5134e2d8139ae167d0d107121f12
git tag -m 'eureka-editor 1.27'  v1.27  c36196d8eac4388d88815f2cb4054127d028ae04
```

### CODE REVIEW

**Comment by selliott512** [comment]
I've only tested Doom, but the change seems straight forward in the other `*.ugh` files.

**Comment by ioan-chera** [comment]
Now that I look at it, I'm not that fond of how it's been implemented even before your fix, I think it's gotta be smarter than merely pushing hardcoded sprite frame characters. For example, it should be able to scan the loaded sprite resources and pick the first frame…

**Comment by selliott512** [comment]
Great, thanks for looking into a better fix. I also thought there should be something to search for a prefix, but then I found a simple and isolated way to fix this one issue.

**Comment by ioan-chera** [comment]
Done.

**Pull request closed without merging**
